# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: 4.2.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-10-28 21:04+0200\n"
"PO-Revision-Date: 2012-07-09 14:35+0100\n"
"Last-Translator: Fibinger Ádám <vfiber[at]gmail dot com>\n"
"Language-Team: Hungarian\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Poedit-Language: Hungarian\n"
"X-Poedit-Country: HUNGARY\n"

#: src/modules/pythoncore/libkvipythoncore.cpp:113
#, fuzzy
msgid "Internal error: Python interpreter not initialized"
msgstr "Belső hiba: python értelmező nincs inicializálva"

#: src/modules/python/libkvipython.cpp:429
msgid "Python execution error:"
msgstr "Python futtatási hiba:"

#: src/modules/python/libkvipython.cpp:42
#, fuzzy
msgid "The pythoncore module can't be loaded: Python support not available"
msgstr ""
"A pythoncore modult nem lehet beltölteni: pyhton támogatás nem elérhető"

#: src/modules/python/libkvipython.cpp:417
#: src/modules/python/libkvipython.cpp:483
#, fuzzy
msgid ""
"The pythoncore module failed to execute the code: something is wrong with "
"the Python support"
msgstr ""
"A pythoncore modulnak nem sikerült a kódot futtatnia: valami probléma van a "
"python támogatással"

#: src/modules/python/libkvipython.cpp:56
#, fuzzy
msgid ""
"This KVIrc executable has been compiled without Python scripting support"
msgstr ""
"Ez a KVIrc példány python szkriptelési támogatás nélkül lett lefordítva"

#: src/modules/python/libkvipython.cpp:43
msgid "To see more details about loading failure try /pythoncore.load"
msgstr ""
"Sikertelen betöltéssel kapcsolatos további információkért próbáld a /"
"pythoncore.load parancsot"
